# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alexUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Alex(object):
    def setupUi(self, Alex):
        Alex.setObjectName("Alex")
        Alex.resize(1129, 841)
        self.centralwidget = QtWidgets.QWidget(Alex)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1131, 871))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("wp2757832.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 510, 191, 201))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("iron-man-jarvis-gif-1.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-10, -20, 451, 221))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("jarvis-gif-6.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(930, 630, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(15, 71, 255);\n"
"border-radius:10px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(930, 720, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(226, 7, 10);\n"
"border-radius:10px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(630, 20, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:24px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(870, 20, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:24px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        Alex.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Alex)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 26))
        self.menubar.setObjectName("menubar")
        Alex.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Alex)
        self.statusbar.setObjectName("statusbar")
        Alex.setStatusBar(self.statusbar)

        self.retranslateUi(Alex)
        QtCore.QMetaObject.connectSlotsByName(Alex)

    def retranslateUi(self, Alex):
        _translate = QtCore.QCoreApplication.translate
        Alex.setWindowTitle(_translate("Alex", "Alex"))
        self.pushButton.setText(_translate("Alex", "Start"))
        self.pushButton_2.setText(_translate("Alex", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Alex = QtWidgets.QMainWindow()
    ui = Ui_Alex()
    ui.setupUi(Alex)
    Alex.show()
    sys.exit(app.exec_())
